I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 208, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 387, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 208, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 387, in script
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 387, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
IOError: Couldn't find file 'gui/(with background(edited in)daus 3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/bootstrap.py", line 326, in bootstrap
    renpy.main.main()
  File "renpy/main.py", line 617, in main
    run(restart)
  File "renpy/main.py", line 148, in run
    renpy.execution.run_context(True)
  File "renpy/execution.py", line 922, in run_context
    context.run()
  File "renpy/common/00start.rpy", line 208, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 387, in script
    $ __gl_test()
  File "renpy/common/00start.rpy", line 208, in script call
    call _gl_test
  File "renpy/common/00gltest.rpy", line 387, in script
    $ __gl_test()
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gltest.rpy", line 387, in <module>
    $ __gl_test()
  File "renpy/common/00gltest.rpy", line 317, in _m1_00gltest__gl_test
    _gl_performance_test()
  File "renpy/common/00gltest.rpy", line 342, in _gl_performance_test
    ui.interact(suppress_underlay=True, suppress_overlay=True)
  File "renpy/ui.py", line 298, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "renpy/display/core.py", line 3062, in interact
    self.start()
  File "renpy/display/core.py", line 2105, in start
    self.post_init()
  File "renpy/display/core.py", line 2183, in post_init
    self.set_icon()
  File "renpy/display/core.py", line 2214, in set_icon
    with renpy.loader.load(icon) as f:
  File "renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'gui/(with background(edited in)daus 3'.

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
web dept 3 1.0
Fri Mar 25 11:33:05 2022
